Export switch subtext setter
Zondax/ledger-zxlib pull request #162
Opened 2024-12-31 16:50 UTC by 0xPxt

- Created `view_set_switch_subtext` so that any app can modify the subtext of a switch according to its needs.

2025-01-02 10:03 UTC, chcmedeiros approved these changes
LGTM!

2025-01-02 17:21 UTC, emmanuelm41 requested changes
Just a few questions

2025-01-02 17:21 UTC, emmanuelm41 commented on app/ui/view_nbgl.c
> +        switches[BLINDSIGN_MODE].subText = "Allows signing transactions without seeing all fields";
Is there enough space to display this on flex/stax? instead of "seeing", maybe "reviewing"? Otherwise, let's ask AI what it thinks about this description haha.

2025-01-02 17:21 UTC, emmanuelm41 commented on app/ui/view_nbgl.c
> -    switches[BLINDSIGN_MODE].subText = "";
Can we add the same description for expert mode? The default one I mean

2025-01-07 12:21 UTC, emmanuelm41 approved these changes

2025-01-07 13:39 UTC, neithanmo approved these changes

2025-01-07 14:33 UTC, merged